language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6

before_install:
  - uname -a
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi
  - df -h
  - ulimit -a
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq gcc-4.8 g++-4.8 && sudo apt-get install -qq gcc-4.9 g++-4.9 && sudo apt-get install -qq gcc-5 g++5 && sudo apt-get install gcc-6 g++-6; fi
script: make CXX=$COMPILER CC=$COMPILER
